# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20190603_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=800),
        ),
    ]
